# Generated by Django 3.0.3 on 2020-03-04 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Уникальный идентификатор')),
                ('date', models.DateTimeField(db_index=True, max_length=200, verbose_name='Дата')),
                ('marked', models.BooleanField(verbose_name='Пометка удаления')),
                ('total_summ', models.FloatField(verbose_name='Сумма документа')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Agent', verbose_name='Агент')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client', verbose_name='Клиент')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Shop', verbose_name='Торговая точка')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice', verbose_name='Ссылка')),
            ],
        ),
    ]
