# Generated by Django 3.0.3 on 2020-03-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='number',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество товара'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена товара'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='invoices.Invoice', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='summ',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма товара'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_summ',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма документа'),
        ),
    ]
