# Generated by Django 3.0.3 on 2020-03-07 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200304_1602'),
        ('invoices', '0002_auto_20200304_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Уникальный идентификатор')),
                ('marked', models.BooleanField(verbose_name='Пометка удаления')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование типа цены')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Уникальный идентификатор')),
                ('marked', models.BooleanField(verbose_name='Пометка удаления')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование промоакции')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_accounting',
            field=models.BooleanField(default=False, verbose_name='БУ'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discont',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Agent', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Shop', verbose_name='Торговая точка'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='core.Product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена товара')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.PriceType', verbose_name='Тип цены')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Product', verbose_name='Тип цены')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoices.Promo', verbose_name='Акция'),
        ),
    ]
