# Generated by Django 3.0.3 on 2020-03-07 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200304_1602'),
        ('invoices', '0003_auto_20200307_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Product', verbose_name='Товар'),
        ),
    ]
