# Generated by Django 3.0.3 on 2020-03-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20200307_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Стату'),
        ),
    ]
