# Generated by Django 3.0.3 on 2020-05-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20200527_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoices.PriceType', verbose_name='Тип цены'),
        ),
    ]
