# Generated by Django 3.0.3 on 2020-05-29 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20200307_1133'),
        ('invoices', '0007_invoice_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visits.Visit', verbose_name='Визит'),
            preserve_default=False,
        ),
    ]
