# Generated by Django 3.0.3 on 2020-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Номер строки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Новая'), (1, 'Создана'), (2, 'Отправлена'), (3, 'Отменена')], db_index=True, default=0, verbose_name='Статус'),
        ),
    ]
