# Generated by Django 3.0.3 on 2020-03-04 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitDate', models.DateTimeField(help_text='Дата/время посещения торговой точки', verbose_name='Дата/время посещения')),
                ('note', models.CharField(help_text='Примечание к посещению', max_length=200, verbose_name='Примечание к посещению')),
                ('result', models.CharField(choices=[('created', 'Создана'), ('visit', 'Посетил'), ('invoice', 'Заявка'), ('canceled', 'Отменено')], help_text='Результат посещения', max_length=20, verbose_name='Результат посещения')),
                ('marked', models.BooleanField(help_text='Пометка удаления', verbose_name='Пометка удаления')),
                ('agent', models.ForeignKey(help_text='Агент', on_delete=django.db.models.deletion.CASCADE, to='core.Agent', verbose_name='Агент')),
                ('shop', models.ForeignKey(help_text='Торговая точка', on_delete=django.db.models.deletion.CASCADE, to='core.Shop', verbose_name='Торговая точка')),
            ],
        ),
    ]
