# Generated by Django 3.0.3 on 2020-03-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='result',
            field=models.CharField(choices=[('created', 'Создана'), ('visit', 'Посетил'), ('invoice', 'Заявка'), ('canceled', 'Отменено')], help_text='Результат посещения', max_length=20, verbose_name='Результат посещения'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitDate',
            field=models.DateTimeField(help_text='Дата/время посещения торговой точки', verbose_name='Дата/время посещения'),
        ),
    ]
