# Generated by Django 3.0.3 on 2020-03-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='result',
            field=models.CharField(choices=[('visit', 'Посетил'), ('invoice', 'Заявка'), ('canceled', 'Отменено')], help_text='Результат посещения', max_length=20, verbose_name='Результат посещения'),
        ),
    ]
