# Generated by Django 3.0.3 on 2020-02-27 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование клиента', max_length=100, verbose_name='Наименование клиента')),
                ('fullName', models.CharField(help_text='Наименование клиента', max_length=250, verbose_name='Наименование клиента')),
                ('inn', models.CharField(help_text='ИНН клиента', max_length=12, verbose_name='ИНН клиента')),
                ('kpp', models.CharField(help_text='КПП клиента', max_length=9, verbose_name='КПП клиента')),
                ('okpo', models.CharField(help_text='ОКПО клиента', max_length=10, verbose_name='ОКПО клиента')),
                ('adress', models.CharField(help_text='Адрес клиента', max_length=250, verbose_name='Адрес клиента')),
                ('phon', models.CharField(help_text='Телефон клиента', max_length=100, verbose_name='Телефон клиента')),
                ('marked', models.BooleanField(help_text='Пометка удаления', verbose_name='Пометка удаления')),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(help_text='Имя агента', max_length=100, verbose_name='Имя агента'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Адрес торговой точки', max_length=200, verbose_name='Адрес торговой точки')),
                ('kpp', models.CharField(help_text='КПП точки', max_length=9, verbose_name='КПП точки')),
                ('phon', models.CharField(help_text='Телефон торговой точки', max_length=100, verbose_name='Телефон торговой точки')),
                ('marked', models.BooleanField(help_text='Пометка удаления', verbose_name='Пометка удаления')),
                ('client', models.ForeignKey(help_text='Клиент', on_delete=django.db.models.deletion.CASCADE, to='main_menu.Client', verbose_name='Клиент')),
            ],
        ),
    ]
