# Generated by Django 3.0.3 on 2020-03-02 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_menu', '0002_auto_20200227_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя агента'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(max_length=250, verbose_name='Адрес клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fullName',
            field=models.CharField(max_length=250, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(db_index=True, max_length=12, verbose_name='ИНН клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.CharField(max_length=9, verbose_name='КПП клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Наименование клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='okpo',
            field=models.CharField(max_length=10, verbose_name='ОКПО клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phon',
            field=models.CharField(max_length=100, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_menu.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='kpp',
            field=models.CharField(max_length=9, verbose_name='КПП точки'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='marked',
            field=models.BooleanField(verbose_name='Пометка удаления'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Адрес торговой точки'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phon',
            field=models.CharField(max_length=100, verbose_name='Телефон торговой точки'),
        ),
        migrations.CreateModel(
            name='AgentShops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_menu.Agent', verbose_name='Агент')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_menu.Shop', verbose_name='Торговая точка')),
            ],
        ),
    ]
