# Generated by Django 3.0.3 on 2020-03-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0003_auto_20200302_2325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentShops',
            new_name='AgentShop',
        ),
    ]
