# Generated by Django 3.0.3 on 2020-03-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200304_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Уникальный идентификатор')),
                ('code', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='Код товара')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('parent_id', models.IntegerField(db_index=True, verbose_name='id родителя')),
                ('marked', models.BooleanField(verbose_name='Пометка удаления')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП клиента'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП точки'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Уникальный идентификатор')),
                ('code', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='Код товара')),
                ('articul', models.CharField(max_length=11, verbose_name='Артикул')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('marked', models.BooleanField(verbose_name='Пометка удаления')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductTree', verbose_name='Родитель')),
            ],
        ),
    ]
