# Generated by Django 3.0.3 on 2020-03-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200304_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fullName',
            new_name='full_name',
        ),
    ]
