# Generated by Django 3.0.3 on 2020-09-14 12:48

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200304_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttree',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='producttree',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.ProductTree'),
        ),
        migrations.AlterField(
            model_name='producttree',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование группы'),
        ),
    ]
