# Generated by Django 3.0.3 on 2020-09-24 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200914_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttree',
            name='level',
        ),
        migrations.RemoveField(
            model_name='producttree',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='producttree',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='producttree',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='producttree',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProductTree', verbose_name='Родитель'),
        ),
    ]
